### ISSUE TITLE
StackOverflowError - additionalProperties

### ISSUE THREAD

**Issue by ogirardot** [pwall567/json-kotlin-schema#6]
Hello, thanks for the good work ! 
There seems to be a infinite loop in the hashCode part of additionalPropertiesSchema : 
![image](https://user-images.githubusercontent.com/353052/145652167-9b690373-ecd5-4348-81cb-8f3f8fd87c93.png)

I write down this issue, I'll try and see to make a PR about it.

**Comment by pwall567** [comment]
Hi - thanks for reporting this.

I had included the parent schema in the equality comparison and hashCode of `AdditionalPropertiesSchema`, and that was always going to lead to infinite recursion.

I have fixed that, along with a similar issue in `AdditionalItemsSchema`.  Version 0.31 is now available in Maven Central - I hope this resolves your problem.

**Comment by ogirardot** [comment]
thanks a lot, checking now

**Comment by ogirardot** [comment]
works perfectly thanks a lot !
