### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by jaredrummler** [pwall567/json-kotlin-schema#9]
Several classes are missing from the project. The following imports failed to resolve:

```kotlin
import net.pwall.json.JSON
import net.pwall.json.JSONBoolean
import net.pwall.json.JSONMapping
import net.pwall.json.JSONNumberValue
import net.pwall.json.JSONSequence
import net.pwall.json.JSONString
import net.pwall.json.JSONValue
import net.pwall.json.pointer.JSONPointer
```

**Comment by pwall567** [comment]
Hi – under normal circumstances your build system will pick those up as transitive dependencies.  All dependencies are listed in the [pom.xml](https://github.com/pwall567/json-kotlin-schema/blob/main/pom.xml) file.

What build system are you using?

**Comment by jaredrummler** [comment]
Hi Peter, 

I apologize; this was an issue with my build system. I will close the issue.  

I was attempting to use your code generator for [NIST V2 1500-100](https://github.com/usnistgov/ElectionResultsReporting/blob/version2/NIST_V2_election_results_reporting.json) but it has a [recursiveRef](#5).
